In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from ydata_profiling import ProfileReport

In [2]:
urinalysis_data = pd.read_csv(r"datasets/urinalysis_tests.csv")

In [3]:
urinalysis_data.head()

,Unnamed: 0,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
0,0,76.0,FEMALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,5.0,1.010,1-3,0-2,OCCASIONAL,RARE,NONE SEEN,OCCASIONAL,NEGATIVE
1,1,9.0,MALE,DARK YELLOW,SLIGHTLY HAZY,NEGATIVE,1+,5.0,1.030,1-3,0-2,RARE,FEW,FEW,MODERATE,NEGATIVE
2,2,12.0,MALE,LIGHT YELLOW,SLIGHTLY HAZY,NEGATIVE,TRACE,5.0,1.030,0-3,0-2,RARE,FEW,MODERATE,RARE,NEGATIVE
3,3,77.0,MALE,BROWN,CLOUDY,NEGATIVE,1+,6.0,1.020,5-8,LOADED,RARE,RARE,NONE SEEN,FEW,NEGATIVE
4,4,29.0,FEMALE,YELLOW,HAZY,NEGATIVE,TRACE,6.0,1.025,1-4,0-2,RARE,RARE,NONE SEEN,FEW,NEGATIVE

In [4]:
urinalysis_data =  urinalysis_data.drop(columns=["Unnamed: 0"])

In [5]:
urinalysis_data.head()

,Age,Gender,Color,Transparency,Glucose,Protein,pH,Specific Gravity,WBC,RBC,Epithelial Cells,Mucous Threads,Amorphous Urates,Bacteria,Diagnosis
0,76.0,FEMALE,LIGHT YELLOW,CLEAR,NEGATIVE,NEGATIVE,5.0,1.010,1-3,0-2,OCCASIONAL,RARE,NONE SEEN,OCCASIONAL,NEGATIVE
1,9.0,MALE,DARK YELLOW,SLIGHTLY HAZY,NEGATIVE,1+,5.0,1.030,1-3,0-2,RARE,FEW,FEW,MODERATE,NEGATIVE
2,12.0,MALE,LIGHT YELLOW,SLIGHTLY HAZY,NEGATIVE,TRACE,5.0,1.030,0-3,0-2,RARE,FEW,MODERATE,RARE,NEGATIVE
3,77.0,MALE,BROWN,CLOUDY,NEGATIVE,1+,6.0,1.020,5-8,LOADED,RARE,RARE,NONE SEEN,FEW,NEGATIVE
4,29.0,FEMALE,YELLOW,HAZY,NEGATIVE,TRACE,6.0,1.025,1-4,0-2,RARE,RARE,NONE SEEN,FEW,NEGATIVE

#### Data definition:

- Age (The age of the patient) Note: Some patients are months old, so the age of these patients are preprocessed by dividing it by a hundred) e.g, 8 MONTHS OLD, 8/100 = 0.08
- Gender (The gender of the patient) Note: Either male or female
- Color (urine color)
- Transparency (urine transparency)
- Glucose (glucose is a type of sugar, and its presence in the urine can be an important indicator of certain health conditions)
- Protein (the presence of protein in the urine is one of the parameters examined to assess kidney function and detect potential)
- pH (the pH level measures the acidity or alkalinity of urine)
- Specific Gravity (urine specific gravity is a measure of the concentration of particles in urine compared to water)
- WBC (White Blood Cells) Note: Also known as leukocytes, white blood cells are a crucial part of the immune system
- RBC (Red Blood Cells) Note: RBC are responsible for carrying oxygen throughout the body
- Epithelial Cells (epithelial cells are cells that line the surfaces and cavities of the body, including the urinary tract)
- Mucous Threads (mucous threads are strands of mucus that can be present in urine)
- Amorphous Urates (amorphous urates are non-crystalline formations in the urine that consist of uric acid)
- Bacteria (presence of bacteria in the urine)
- Diagnosis (UTI Diagnosis) Note: Either NEGATIVE or POSITIVE

In [6]:
print(f"The dataset contains {urinalysis_data.shape[0]} rows and {urinalysis_data.shape[1]} columns.")

The dataset contains 1436 rows and 15 columns.

In [7]:
urinalysis_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1436 non-null   float64
 1   Gender            1436 non-null   object
 2   Color             1435 non-null   object
 3   Transparency      1436 non-null   object
 4   Glucose           1436 non-null   object
 5   Protein           1436 non-null   object
 6   pH                1436 non-null   float64
 7   Specific Gravity  1436 non-null   float64
 8   WBC               1436 non-null   object
 9   RBC               1436 non-null   object
 10  Epithelial Cells  1436 non-null   object
 11  Mucous Threads    1436 non-null   object
 12  Amorphous Urates  1436 non-null   object
 13  Bacteria          1436 non-null   object
 14  Diagnosis         1436 non-null   object
dtypes: float64(3), object(12)
memory usage: 168.4+ KB

One missing value was found

In [8]:
urinalysis_data = urinalysis_data.dropna(subset=['Color'])

The datasets is clean ready for analysis

### Exploratory Data Analysis (EDA)

In [9]:
# EDA using ydata_profiling
profile = ProfileReport(urinalysis_data, title= 'my report', explorative=True)
profile.to_file(r"reports/urinalysis_data_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 15/15 [00:00<00:00, 22.97it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [10]:
urinalysis_data.to_csv(r"datasets/urinalysis_data_cleaned.csv", index=False)